apps/Goods/urls.py
from django.urls import re_path
from apps.Goods.views import MainView, DetailView, ListView

urlpatterns = [
    re_path(r'main', MainView.as_view(), name='main'),
    re_path(r'detail/(?P<goods_id>.*)', DetailView.as_view(), name='detail'),
    re_path(r'list/(?P<type_id>.*)/(?P<page>.*)', ListView.as_view(), name='list'),
]

apps/Users/urls.py
from django.urls import re_path
from django.contrib.auth.decorators import login_required
from apps.Users import views
from apps.Users.views import RedirectLine, ActiveView, LoginView, UserOrder, UserInfo, UserAddress, LogOut

urlpatterns = [
    # re_path(r'^register$', views.register, name='register'),
    # re_path(r'^login$', views.login, name='login'),
    re_path(r'^register$', RedirectLine.as_view(), name='register'),
    re_path(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),
    re_path(r'^login$', LoginView.as_view(), name='login'),
    re_path(r'^center$', UserInfo.as_view(), name='userinfo'),
    re_path(r'^userorder/(?P<page>.*)$', UserOrder.as_view(), name='userorder'),
    re_path(r'^address$', UserAddress.as_view(), name='useraddress'),
    re_path(r'^logout$', LogOut.as_view(), name='logout'),
]

apps/cart/urls.py
from django.urls import path, re_path, include
from .views import CartAddView, CartView, UpCartView, DelCartView

urlpatterns = [
    re_path(r'^addcart$', CartAddView.as_view(), name='addcart'),
    re_path(r'^cart$', CartView.as_view(), name='cart'),
    re_path(r'^updatecart$', UpCartView.as_view(), name='upcart'),
    re_path(r'^delete$', DelCartView.as_view(), name='delete'),
]

apps/order/urls.py
from django.urls import path, re_path, include
from .views import PlaceView, CommitView, OrderPayView, PaySearchView, CommentView

urlpatterns = [
    re_path(r'^place$', PlaceView.as_view(), name='place'),
    re_path(r'^commit$', CommitView.as_view(), name='commit'),
    re_path(r'^pay$', OrderPayView.as_view(), name='pay'),
    re_path(r'^checkorder$', PaySearchView.as_view(), name='checkorder'),
    re_path(r'^comment/(?P<order_id>.*)$', CommentView.as_view(), name='comment'),

]

day_project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    re_path(r'^search/', include('haystack.urls')),  # 分词系统
    re_path(r'^user/', include(('Users.urls', 'Users'), namespace='user')),
    re_path(r'^order/', include(('order.urls', 'order'), namespace='order')),
    re_path(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    re_path(r'', include(('Goods.urls', 'Goods'), namespace='goods')),

]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from apps.Goods.models import GoodsSKU
from django_redis import get_redis_connection
from django.contrib.auth.mixins import LoginRequiredMixin


class CartView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user

        conn = get_redis_connection('default')
        cart_key = f'cart_{user.id}'
        sku_dict = conn.hgetall(cart_key)

        total_count = 0
        sku_list = []
        for sku_id, count in sku_dict.items():
            sku = GoodsSKU.objects.get(id=sku_id)

            ment = sku.price * int(count)
            sku.count = int(count)
            sku.ment = ment
            sku_list.append(sku)

            total_count += int(count)

        context = {
            'sku_list': sku_list,
            'total_count': total_count,
        }

        return render(request, 'cart.html', context)


class CartAddView(View):

    def post(self, request):

        user = request.user

        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        if not all([sku_id, count]):
            return JsonResponse({'res': 0, 'errmsg': '数据不完整'})

        try:
            count = int(count)
        except:
            return JsonResponse({'res': 1, 'errmsg': '数据错误'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except sku.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '查不到商品'})

        sku_stock = sku.stock

        conn = get_redis_connection('default')
        cart_key = f'cart_{user.id}'
        # 如果hget没有查到 hget返回None
        cart_non = conn.hget(cart_key, sku_id)

        # 如果redis中有对应的sku_id 就将sku_id对应的值相加
        if cart_non:
            count += int(cart_non)

        if count > sku_stock:
            return JsonResponse({'res': 3, 'errmsg': '库存不足'})

        conn.hset(cart_key, sku_id, count)

        cart_len = conn.hlen(cart_key)

        return JsonResponse({'res': 4, 'cart_len': cart_len, 'message': '添加成功'})


class UpCartView(View):
    def post(self, request):
        user = request.user

        if not user.is_authenticated:
            return JsonResponse({'res':0, 'errmsg':'没有登录'})

        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不全'})

        try:
            is_sku = GoodsSKU.objects.get(id=sku_id)
        except is_sku.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        try:
            count = int(count)
        except is_sku.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品数量出错'})

        sku_stock = is_sku.stock

        if sku_stock < int(count):
            return JsonResponse({'res': 4, 'count': sku_stock, 'errmsg': '库存不足'})

        conn = get_redis_connection('default')
        cart_key = f'cart_{user.id}'

        conn.hset(cart_key, sku_id, count)

        sku_dict = conn.hgetall(cart_key)
        total_count = 0
        for sku, count in sku_dict.items():
            total_count += int(count)

        return JsonResponse({'res': 5, 'message': '成功', 'total_count': total_count})


class DelCartView(View):
    def post(self, request):

        user = request.user

        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '用户未登录'})

        sku_id = request.POST.get('sku_id')

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except sku.DoesNotExist:
            return JsonResponse({'res': 1, 'errmsg': '商品不存在'})

        conn = get_redis_connection('default')
        sku_key = f'cart_{user.id}'
        conn.hdel(sku_key, sku_id)
        print(sku_id)
        total_count = 0
        all_sku = conn.hgetall(sku_key)
        for id, count in all_sku.items():
            total_count += int(count)

        return JsonResponse({'res': 3, 'total_count': total_count, 'message': '成功'})

apps/order/views.py
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse
from django.views.generic import View
from django_redis import get_redis_connection
from apps.Goods.models import GoodsSKU
from apps.order.models import OrderInfo, OrderGoods
from apps.Users.models import Address
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime
from django.db import transaction
from django.conf import settings
from alipay import AliPay
import os


class PlaceView(LoginRequiredMixin, View):
    def post(self, request):
        user = request.user

        sku_ids = request.POST.getlist('sku_id')

        total_count = 0
        total_price = 0
        skus = []
        for sku_id in sku_ids:
            sku = GoodsSKU.objects.get(id=sku_id)

            conn = get_redis_connection('default')
            key = f'cart_{user.id}'
            count = conn.hget(key, sku_id)
            price =sku.price
            amount = price * int(count)
            # 总价格和总数量
            total_count += int(count)
            total_price += amount

            sku.amount = amount
            sku.count = int(count)

            skus.append(sku)

        addr = Address.object.filter(user=user)

        freight = 10

        payment = total_price + freight

        sku_con = ','.join(sku_ids)

        context = {
            'skus': skus,
            'total_count': total_count,
            'total_price': total_price,
            'addr': addr,
            'payment': payment,
            'freight': freight,
            'sku_con': sku_con,
        }

        return render(request, 'order.html', context)


class CommitView(View):
    # sql事务
    @transaction.atomic
    def post(self, request):

        user = request.user

        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '用户未登录'})

        addr_id = request.POST.get('add_id')
        pay_id = request.POST.get('pay_id')
        skus = request.POST.get('skus')

        if not all([addr_id, pay_id, skus]):
            return JsonResponse({'res': 1, 'errmsg': '数据不全'})

        skus_id = skus.split(',')

        if pay_id not in OrderInfo.PAY_METHOD_DIC.keys():
            return JsonResponse({'res': 2, 'errmsg': '无效支付方式'})

        try:
            addr = Address.object.get(id=addr_id)
        except addr.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '无效地址'})

        # todo:订单核心业务
        order_id = datetime.now().strftime('%Y%m%d%H%M%S')+str(user.id)

        tr_price =10

        total_count = 0
        total_price = 0

        # todo:创建保存点
        save_id = transaction.savepoint()

        # 创建订单表
        order = OrderInfo.objects.create(order_id=order_id, pay_method=pay_id, product_count=total_count, product_price=total_price, transit_price=tr_price, user=user, addr=addr, )

        conn = get_redis_connection('default')
        key = f'cart_{user.id}'

        # todo:循环购物车传过来的商品id 创建订单商品
        for sku_id in skus_id:
            for i in range(3):
                try:
                    sku = GoodsSKU.objects.get(id=sku_id)
                except sku.DoesNotExist:
                    # todo:出错 事务回滚到保存点
                    transaction.savepoint_rollback(save_id)
                    return JsonResponse({'res': 4, 'errmsg': '商品不存在'})

                count = conn.hget(key, sku_id)



                if int(count) > sku.stock:
                    transaction.savepoint_rollback(save_id)
                    return JsonResponse({'res': 6, 'errmsg': '库存不足'})

                # todo：更新商品库存 和销量 乐观锁
                origin_stock = sku.stock
                new_stock = origin_stock - int(count)
                new_sales = origin_stock + sku.sales

                # todo:在更新时判断 之前取得的库存是否和现在相同 加乐观锁 返回更新的条数
                new_num = GoodsSKU.objects.filter(id=sku_id, stock=origin_stock).update(stock=new_stock, sales=new_sales)

                if new_num == 0:
                    # todo:尝试三次 若三次都没下单成功就失败
                    if i == 2:
                        transaction.savepoint_rollback(save_id)
                        return JsonResponse({'res': 7, 'errmsg': '下单失败'})
                    continue

                OrderGoods.objects.create(
                    count=count,
                    price=sku.price,
                    product=sku,
                    order_info=order
                )

                amount = int(count)*sku.price

                total_count += int(count)
                total_price += amount

                break

        # todo:更新订单表
        order.product_count = total_count
        order.product_price = total_price
        order.save()

        # todo: 传列表参时 参数前加* [1,2] (key, *[1,2]) 相当于 (key, 1，2)
        conn.hdel(key, *skus_id)
        return JsonResponse({'res': 5, 'message': '订单创建成功', })


class OrderPayView(View):

    def post(self, request):
        # todo:判断是否登录
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '用户未登录'})

        # todo:接收参数 判断参数
        order_id = request.POST.get('order_id')
        if not order_id:
            return JsonResponse({'res': 1, 'errmsg': '参数为空'})

        # 查询订单
        try:
            order = OrderInfo.objects.get(order_id=order_id, user=user, pay_method=3, order_status=1)
        except order.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '订单不存在'})

        private_key = open('apps/order/private2048.txt').read()
        public_key = open('apps/order/alipay_public_key.pem').read()

        # 初始化api
        alipay = AliPay(
            appid="2021000117695387",
            app_notify_url=None,  # 默认回调url
            app_private_key_string=str(private_key),
            # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
            alipay_public_key_string=str(public_key),
            sign_type="RSA2",  # RSA 或者 RSA2
            debug=True,  # 默认False
        )

        subject = "iphone 11 pro"

        # 电脑网站支付，需要跳转到https://openapi.alipay.com/gateway.do? + order_string
        total_amount = order.product_price + order.transit_price  # DecimalField类型 会转换从json类型

        order_string = alipay.api_alipay_trade_page_pay(
            out_trade_no=str(order_id),
            total_amount=str(total_amount),
            subject=subject,
            return_url='https://www.baidu.com/',
            notify_url='https://example.com/notify'  # 可选, 不填则使用默认notify url
        )

        pay_url = 'https://openapi.alipaydev.com/gateway.do?' + order_string

        return JsonResponse({'res': 3, 'pay_url': pay_url})


class PaySearchView(View):
    '''
    订单状态查询
    '''
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '用户未登录'})

        # todo:接收参数 判断参数
        order_id = request.POST.get('order_id')
        if not order_id:
            return JsonResponse({'res': 1, 'errmsg': '参数为空'})

        # 查询订单
        try:
            order = OrderInfo.objects.get(order_id=order_id, user=user, pay_method=3, order_status=1)
        except order.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '订单不存在'})

        private_key = open('apps/order/private2048.txt').read()
        public_key = open('apps/order/alipay_public_key.pem').read()

        # 初始化api
        alipay = AliPay(
            appid="2021000117695387",
            app_notify_url=None,  # 默认回调url
            app_private_key_string=str(private_key),
            # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
            alipay_public_key_string=str(public_key),
            sign_type="RSA2",  # RSA 或者 RSA2
            debug=True,  # 默认False
        )

        respone = alipay.api_alipay_trade_query(order_id)

        code = respone.get('code')
        while True:
            if code == '10000' and respone.get('trade_status') == 'TRADE_SUCCESS':

                trade_no = respone.get('trade_no')

                order.trance_num = trade_no
                order.order_status = 4
                order.save()

                return JsonResponse({'res': 3, 'success': '订单已支付'})

            elif code == '40004' or (code == 10000 and respone.get('trade_status') == 'WAIT_BUYER_PAY'):
                import time
                time.sleep(5)
                continue
            else:
                print(code)
                return JsonResponse({'res': 4, 'errmsg': '支付失败'})


class CommentView(LoginRequiredMixin, View):
    """订单评论"""

    def get(self, request, order_id):
        """提供评论页面"""
        user = request.user

        try:
            order = OrderInfo.objects.get(order_id=order_id, user=user)
        except:
            return redirect(reverse('user:userorder'))

        # 根据订单的状态获取订单的状态标题
        order.status_name = OrderInfo.ORDER_status_dic[order.order_status]

        # 获取订单商品信息
        order_skus = OrderGoods.objects.filter(order_info=order)
        for order_sku in order_skus:
            amount = order_sku.count * order_sku.price
            # 动态给order_sku增加属性amount,保存商品小计
            order_sku.amount = amount
        # 动态给order增加属性order_skus, 保存订单商品信息
        order.order_skus = order_skus

        # 使用模板
        return render(request, "order_comment.html", {"order": order})

    def post(self, request, order_id):
        """处理评论内容"""
        user = request.user

        try:
            order = OrderInfo.objects.get(order_id=order_id, user=user)
        except OrderInfo.DoesNotExist:
            return redirect(reverse("user:userorder"))

        # 获取评论条数
        total_count = request.POST.get("total_count")
        total_count = int(total_count)

        # 循环获取订单中商品的评论内容

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block css %}{% endblock css %}
    {% block js %}{% endblock js %}

</head>
<body>
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

				{% if user.is_authenticated %}
             <div class="user_link fl">
                <a href="{% url 'user:userinfo' %}">欢迎您：{{user.username}}</a>
                <span>|</span>
                    <a href="{% url 'user:logout' %}">退出</a>
                <span>|</span>
                <a href="{% url 'user:userinfo' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'cart:cart' %}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'user:userorder' 1 %}">我的订单</a>
            </div>
            {% else %}
            <div class="login_btn fl">
                <a href="{% url 'user:login' %}">登录</a>
                <span>|</span>
                <a href="{% url 'user:register' %}">注册</a>
            </div>
            {% endif %}

			</div>
		</div>
	</div>

    <div class="search_bar clearfix">
		<a href="/goods/main" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="/cart/" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_num }}</div>
		</div>
	</div>

    <div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

    {% block main_body %}

    {% endblock main_body %}


	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
</body>
</html>

templates/base_cart.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block css %}{% endblock css %}
    {% block js %}{% endblock js %}

</head>
<body>
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
            {% if user.is_authenticated %}
             <div class="user_link fl">
                <a href="{% url 'user:userinfo' %}">欢迎您：{{user.username}}</a>
                <span>|</span>
                 <a href="{% url 'user:logout' %}">退出</a>
                <span>|</span>
                <a href="{% url 'user:userinfo' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'cart:cart' %}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'user:userorder' 1%}">我的订单</a>
            </div>
            {% else %}
            <div class="login_btn fl">
                <a href="{% url 'user:login' %}">登录</a>
                <span>|</span>
                <a href="{% url 'user:register' %}">注册</a>
            </div>
            {% endif %}
			</div>
		</div>
	</div>

    <div class="search_bar clearfix">
		<a href="/goods/main" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>

    <div class="main_con clearfix">
  <div class="left_menu_con clearfix">
  <h3>用户中心</h3>
  <ul>
    <li><a href="{% url 'user:userinfo' %}"{% if info %} class="active"{% endif %}>· 个人信息</a></li>
    <li><a href="{% url 'user:userorder' 1 %}"{% if order %} class="active"{% endif %}>· 全部订单</a></li>
    <li><a href="{% url 'user:useraddress' %}"{% if site %} class="active"{% endif %}>· 收货地址</a></li>
  </ul>
  </div>
        {% block main_body %}

    {% endblock main_body %}
</div>




	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
{% block base_js %}
{% endblock base_js %}
</html>

templates/footer.html
{#<div class="footer no-mp">#}
{#		<div class="foot_link">#}
{#			<a href="#">关于我们</a>#}
{#			<span>|</span>#}
{#			<a href="#">联系我们</a>#}
{#			<span>|</span>#}
{#			<a href="#">招聘人才</a>#}
{#			<span>|</span>#}
{#			<a href="#">友情链接</a>#}
{#		</div>#}
{#		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>#}
{#		<p>电话：010-****888    京ICP备*******8号</p>#}
{#	</div>#}

templates/login.html
{% extends 'base_user.html' %}
{% load static %}
{% block title %}
    天天生鲜-登录
{% endblock title %}
{% block css %}
            <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
        {% endblock css %}
    {% block js %}
        <script type="text/javascript" src="{% static 'js/jquery1.11.0.js' %}"></script>
	    <script type="text/javascript" src="{% static 'js/login.js' %}"></script>
    {% endblock js %}

    {% block main_body %}
        <div class="login_top clearfix">
		    <a href="#" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	    </div>

        <div class="login_form_bg">
		<div class="login_form_wrap clearfix">

			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">

				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>

				<div class="form_input">

					<form id="form" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>

						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>

						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>

						<input id="lo" type="submit" name="" value="登录" class="input_submit">
					</form>

				</div>
			</div>
		</div>
	</div>
{{ errmsg }}
    {% endblock main_body %}

templates/p_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block css %}{% endblock %}
</head>
<body>
<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

				{% if user.is_authenticated %}
             <div class="user_link fl">
                <a href="{% url 'user:userinfo' %}">欢迎您：{{user.username}}</a>
                <span>|</span>
                    <a href="{% url 'user:logout' %}">退出</a>
                <span>|</span>
                <a href="{% url 'user:userinfo' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'cart:cart' %}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'user:userorder' 1%}">我的订单</a>
            </div>
            {% else %}
            <div class="login_btn fl">
                <a href="{% url 'user:login' %}">登录</a>
                <span>|</span>
                <a href="{% url 'user:register' %}">注册</a>
            </div>
            {% endif %}

			</div>
		</div>
	</div>
    <div class="search_bar clearfix">
    <a href="/goods/main" class="logo fl"><img src="{% static 'images/logo.png'%}"></a>
    <form method='get' action="/search/" target="_blank">
    <div class="search_con fl">
        <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
        <input type="submit" class="input_btn fr" name="" value="搜索">
    </div>
    </form>


    {% if user.is_authenticated %}
  <div class="guest_cart fr">
        <a href="#" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count">{{ cart_num }}</div>
    </div>
        {% else %}
        <div class="guest_cart fr">
            <a href="{% url 'user:login' %}" class="cart_name fl">我的购物车</a>
        </div>
    {% endif %}
</div>
    <div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                {% for type in types %}
                    <li><a href="{% url 'goods:list' type.id 1%}" class="{{ type.logo }}">{{ type.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>

{% block detail %}
{% endblock detail%}

<div class="main_wrap clearfix">
    <div class="l_wrap fl clearfix">
        <div class="new_goods">
            <h3>新品推荐</h3>
            <ul>
                {%for sk in sku_type%}
                <li>
                    <a href="{% url 'goods:detail' sk.id %}"><img src="{{ sk.image.url }}"></a>
                    <h4><a href="{% url 'goods:detail' sk.id %}">{{sk.name}}</a></h4>
                    <div class="prize">￥{{sk.price}}</div>
                </li>
                {%endfor%}
            </ul>
        </div>
    </div>
{% block list %}
{% endblock list %}
</div>
    <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    <script src="{% static 'js/jquery1.11.0.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>